### ISSUE TITLE
Unable to browse packages at packages.adoptium.net and yum installation failed on RHEL

### ISSUE THREAD

**Issue by simon-cdf** [adoptium/installer#570]
### Please provide a brief summary of the bug

Hello,

I'm trying to download the rpm for temurin-8-jdk to install on a RHEL 7.9 system that don't have access to the internet.

According to this article ...
https://adoptium.net/installation/linux/#_centosrhelfedora_instructions

I should be able to view the supported version list and rpms at:
https://packages.adoptium.net/ui/native/rpm/

However, when I visit the site all I can see is a JFrog login page. I tried signing in with the "Sign In With GitHub" option but it returns a "login with oauth error - OAuth state cookie missing" error.

Then I tried to follow the official installation instructions for RHEL and attempted to yum install on a RHEL 7.9 machine with internet access, but I received this error after the yum install step:

failure: repodata/repomd.xml from Adoptium: [Errno 256] No more mirrors to try.
https://packages.adoptium.net/artifactory/rpm/rhel/7Server/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

Can you please advise? Thanks!

### Expected Results

- Public users should be able to browse and download all versions of installation packages at https://packages.adoptium.net/ui/native/rpm/
- yum install on RHEL 7 should not end with a 404 error.

### Actual Results

- https://packages.adoptium.net/ui/native/rpm/ requires login and not showing available packages to the public.
- yum install temurin-8-jdk on RHEL 7.9 ends with a 404 error. Installation failed.

### What Java Version are you using?

8

### What is your operating system and platform?

RHEL 7.9

**Comment by gdams** [comment]
This should be fixed now. Let me know (closing for now)

**Comment by urskog84** [comment]
Still have this problem with Rhel 7

https://packages.adoptium.net/artifactory/rpm/rhel/7Server/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

after change to 

```
# /etc/yum.repos.d/Adoptium.repo

[Adoptium]
baseurl = https://packages.adoptium.net/artifactory/rpm/rhel/7/$basearch
gpgcheck = 1
gpgkey = https://packages.adoptium.net/artifactory/api/gpg/key/public
name = Adoptium
```
