### ISSUE TITLE
Debian Bookworm repository for Temurin 21 not working

### ISSUE THREAD

**Issue by jinzo** [adoptium/installer#766]
**What are you trying to do?**
Install temurin-21-jdk on Debian Bookworm

**Observed behaviour:**
```bash
root@bennu:~# cat /etc/apt/sources.list.d/adoptium.list
deb [signed-by=/etc/apt/keyrings/adoptium.asc] https://packages.adoptium.net/artifactory/deb bookworm main
root@bennu:~# apt update
Hit:1 http://deb.debian.org/debian bookworm InRelease
Get:2 http://security.debian.org/debian-security bookworm-security InRelease [48.0 kB]              
Hit:3 https://download.docker.com/linux/debian bookworm InRelease                                   
Hit:4 http://deb.debian.org/debian bookworm-updates InRelease                                                   
Get:5 https://packages.adoptium.net/artifactory/deb bookworm InRelease [6,638 B]                                
Fetched 54.6 kB in 1s (55.7 kB/s)    
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
root@bennu:~# apt install temurin-21-jdk
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  adoptium-ca-certificates alsa-topology-conf alsa-ucm-conf fontconfig-config fonts-dejavu-core fonts-dejavu-extra java-common libasound2 libasound2-data libfontconfig1
  libxi6 libxrender1 libxtst6 p11-kit p11-kit-modules x11-common
Suggested packages:
  default-jre libasound2-plugins alsa-utils
The following NEW packages will be installed:
  adoptium-ca-certificates alsa-topology-conf alsa-ucm-conf fontconfig-config fonts-dejavu-core fonts-dejavu-extra java-common libasound2 libasound2-data libfontconfig1
  libxi6 libxrender1 libxtst6 p11-kit p11-kit-modules temurin-21-jdk x11-common
0 upgraded, 17 newly installed, 0 to remove and 0 not upgraded.
Need to get 177 MB/183 MB of archives.
After this operation, 378 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Err:1 https://packages.adoptium.net/artifactory/deb bookworm/main amd64 temurin-21-jdk amd64 21.0.1.0.0+12
  400  Bad Request [IP: 151.101.243.42 443]
E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-${VERSION}/temurin-21-jdk_21.0.1.0.0%2b12_amd64.deb  400  Bad Request [IP: 151.101.243.42 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

```

**Any other comments:**
Fresh Bookworm install from today, almost nothing else installed than base netinstall. Lookslike something is wrong and ```${VERSION}``` did not get replaced with 21 with the debian repository build.

**Comment by sxa** [comment]
There have been a few similar issues raised recently, although in each case I have been unable to reproduce it. It feels like a caching issue somewhere. I've transferred this to the installer repository as it's the most appropriate place for it.

**Comment by mrairzuk** [comment]
Same today for Ubuntu 22.04.3 LTS (Jammy Jellyfish).

Fails on all JDK installed (11 and 17)

Err:1 https://packages.adoptium.net/artifactory/deb jammy/main amd64 temurin-11-jdk amd64 11.0.21.0.0+9
  400  Bad Request [IP: 151.101.247.42 443]
Err:2 https://packages.adoptium.net/artifactory/deb jammy/main amd64 temurin-17-jdk amd64 17.0.9.0+9
  400  Bad Request [IP: 151.101.247.42 443]
E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-${VERSION}/temurin-11-jdk_11.0.21.0.0%2b9_amd64.deb  400  Bad Request [IP: 151.101.247.42 443]
E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-${VERSION}/temurin-17-jdk_17.0.9.0%2b9_amd64.deb  400  Bad Request [IP: 151.101.247.42 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by jennyowen** [comment]
It looks as though there was some problem with whatever script updated the deb repository metadata.
If you look at the Packages files, eg:
```
curl https://packages.adoptium.net/artifactory/deb/dists/jammy/main/binary-amd64/Packages
```
The latest patches have file redirects with `${VERSION}` inside, instead of whatever **value** `${VERSION}` actually is.

For example `temurin-11-jdk_11.0.21` redirects to file:
pool/main/t/temurin-${VERSION}/temurin-11-jdk_11.0.21.0.0+9_amd64.deb

but `temurin-11-jdk_11.0.20.1` redirects to:
pool/main/t/temurin-11/temurin-11-jdk_11.0.20.1.0+1_amd64.deb
Where `${VERSION}` is correctly replaced by `11`.

That's why it works when you specify an older version.

And to save anyone from looking up what those versions are...
* java 21: `apt install temurin-21-jdk=21.0.0.0.0+35`
* java 17: `apt install temurin-17-jdk=17.0.8.1.0+1`
* java 11: `apt install temurin-11-jdk=11.0.20.1.0+1`

**Comment by statoon54** [comment]
> It looks as though there was some problem with whatever script updated the deb repository metadata. If you look at the Packages files, eg:
> 
> ```
> curl https://packages.adoptium.net/artifactory/deb/dists/jammy/main/binary-amd64/Packages
> ```
> 
> The latest patches have file redirects with `${VERSION}` inside, instead of whatever **value** `${VERSION}` actually is.
> 
> For example `temurin-11-jdk_11.0.21` redirects to file: `pool/main/t/temurin-${VERSION}/temurin-11-jdk_11.0.21.0.0+9_amd64.deb`
> 
> but `temurin-11-jdk_11.0.20.1` redirects to: `pool/main/t/temurin-11/temurin-11-jdk_11.0.20.1.0+1_amd64.deb` Where `${VERSION}` is correctly replaced by `11`.
> 
> That's why it works when you specify an older version.
> 
> And to save anyone from looking up what those versions are...
> 
> * java 21: `apt install temurin-21-jdk=21.0.0.0.0+35`
> * java 17: `apt install temurin-17-jdk=17.0.8.1.0+1`
> * java 11: `apt install temurin-11-jdk=11.0.20.1.0+1`

The Folder ${VERSION} exists https://adoptium.jfrog.io/ui/repos/tree/General/deb/pool/main/t/temurin-$%7BVERSION%7D

But the encoding is bad somewhere with ${VERSION}.

**Comment by eolivelli** [comment]
I am seeing the same problem.
I hope we can fix this soon.
Thanks for anyone who is working on this problem

**Comment by Quinteger** [comment]
Same issue on Linux Mint 21.2, both in Update manager and `apt upgrade`:
```
E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-${VERSION}/temurin-11-jdk_11.0.21.0.0%2b9_amd64.deb  400  Bad Request [IP: 146.75.119.42 443]
E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-${VERSION}/temurin-17-jdk_17.0.9.0%2b9_amd64.deb  400  Bad Request [IP: 146.75.119.42 443]
E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-${VERSION}/temurin-21-jdk_21.0.1.0.0%2b12_amd64.deb  400  Bad Request [IP: 146.75.119.42 443]

```

**Comment by tnymlr** [comment]
Interesting note. If I just get into docker: `docker run -it $image /bin/bash` and run commands there, it works. If I run them from Dockerfile - same error with BAD_REQUEST.

**Comment by jakuboskera** [comment]
When it will fixed? I am trying to build ubuntu22 [runner-images](https://github.com/actions/runner-images) which depends on this and due to thi bug the build is failing.

**Comment by sophia-guo** [comment]
temurin-${VERSION}/ has been deleted. Is this still a issue?

**Comment by sophia-guo** [comment]
@tnymlr works for x64 now, correct? Thanks!

**Comment by slovdahl** [comment]
`temurin-11-jdk` and `temurin-21-jdk` work now, but not `temurin-17-jdk` yet.

```
Err:1 https://packages.adoptium.net/artifactory/deb jammy/main amd64 temurin-17-jdk amd64 17.0.9.0+9
  400  Bad Request [IP: 151.101.247.42 443]
E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-${VERSION}/temurin-17-jdk_17.0.9.0%2b9_amd64.deb  400  Bad Request [IP: 151.101.247.42 443]
```

**Comment by jakuboskera** [comment]
> `temurin-11-jdk` and `temurin-21-jdk` work now, but not `temurin-17-jdk` yet.
> 
> ```
> Err:1 https://packages.adoptium.net/artifactory/deb jammy/main amd64 temurin-17-jdk amd64 17.0.9.0+9
>   400  Bad Request [IP: 151.101.247.42 443]
> E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-${VERSION}/temurin-17-jdk_17.0.9.0%2b9_amd64.deb  400  Bad Request [IP: 151.101.247.42 443]
> ```

can confirm `temurin-8-jdk` and `temurin-11-jdk` works, `temurin-17-jdk` not...

**Comment by karianna** [comment]
Hi folks, we're aware of the issue and are investigating with our CDN and package repo providers.

**Comment by tnymlr** [comment]
@sophia-guo yes, x64. Thank's again =).

**Comment by iAweX** [comment]
> temurin-${VERSION}/ has been deleted. Is this still a issue?

Not works for temurin-17-jdk

**Comment by lhotari** [comment]
Quick way to see if the problem isn't yet fixed:
```
❯ curl -s 'https://packages.adoptium.net/artifactory/deb/dists/jammy/main/binary-amd64/Packages' |grep '${VERSION}'
Filename: pool/main/t/temurin-${VERSION}/temurin-21-jdk_21.0.1.0.0+12_amd64.deb
Filename: pool/main/t/temurin-${VERSION}/temurin-17-jdk_17.0.9.0+9_amd64.deb
Filename: pool/main/t/temurin-${VERSION}/temurin-11-jdk_11.0.21.0.0+9_amd64.deb
Filename: pool/main/t/temurin-${VERSION}/temurin-11-jre_11.0.21.0.0+9_amd64.deb
Filename: pool/main/t/temurin-${VERSION}/temurin-17-jre_17.0.9.0+9_amd64.deb
```
As long as you get this type of result, the problem remains.

By searching the repository content, `${VERSION}` is only referenced from https://github.com/adoptium/installer/blob/master/linux/Jenkinsfile . Perhaps there's some quotes issue in Jenkinsfile?

**Comment by lhotari** [comment]
Well, it seems to be an issue only in the packages index. The same version is duplicated in the index and the invalid one gets picked.

For example:
```
❯ curl -s 'https://packages.adoptium.net/artifactory/deb/dists/jammy/main/binary-amd64/Packages' |grep jdk_21.0.1.0.0
Filename: pool/main/t/temurin-${VERSION}/temurin-21-jdk_21.0.1.0.0+12_amd64.deb
Filename: pool/main/t/temurin-21/temurin-21-jdk_21.0.1.0.0+12_amd64.deb
```
I guess the index needs to be fixed or the version bumped?

**Comment by lhotari** [comment]
It looks like the Packages index is now fixed and this issue is resolved. Thanks for fixing this!

**Comment by statoon54** [comment]
> It looks like the Packages index is now fixed and this issue is resolved. Thanks for fixing this!

I confirm. x64 & temurin 17 works.

**Comment by ByCzech** [comment]
Fixed. Working for me too.

**Comment by domth** [comment]
It's NOT fixed!
Using [these scripts](https://github.com/actions/runner-images/), I still get the error randomly.

```
2023/10/29 09:21:25 ui: 2023-10-29T09:21:25Z:     azure-arm.ubuntu20: After this operation, 214 MB of additional disk space will be used.
2023/10/29 09:21:25 ui: 2023-10-29T09:21:25Z:     azure-arm.ubuntu20: Get:1 https://packages.adoptium.net/artifactory/deb focal/main amd64 adoptium-ca-certificates all 1.0.2-1 [2304 B]
2023/10/29 09:21:25 ui: 2023-10-29T09:21:25Z:     azure-arm.ubuntu20: Get:2 https://packages.adoptium.net/artifactory/deb focal/main amd64 temurin-8-jdk amd64 8.0.382.0.0+5 [84.8 MB]
2023/10/29 09:21:25 ui: 2023-10-29T09:21:25Z:     azure-arm.ubuntu20: Get:3 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 p11-kit-modules amd64 0.23.20-1ubuntu0.1 [231 kB]
2023/10/29 09:21:26 ui: 2023-10-29T09:21:26Z:     azure-arm.ubuntu20: Get:4 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 p11-kit amd64 0.23.20-1ubuntu0.1 [93.8 kB]
2023/10/29 09:21:26 ui: 2023-10-29T09:21:26Z:     azure-arm.ubuntu20: Get:5 http://azure.archive.ubuntu.com/ubuntu focal/main amd64 fonts-dejavu-extra all 2.37-1 [1953 kB]
2023/10/29 09:21:26 ui: 2023-10-29T09:21:26Z:     azure-arm.ubuntu20: Get:6 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 fonts-dejavu all 2.37-1 [3130 B]
2023/10/29 09:21:26 ui: 2023-10-29T09:21:26Z:     azure-arm.ubuntu20: Get:7 http://azure.archive.ubuntu.com/ubuntu focal/main amd64 java-common all 0.72 [6816 B]
2023/10/29 09:21:27 ui: 2023-10-29T09:21:27Z:     azure-arm.ubuntu20: Err:2 https://packages.adoptium.net/artifactory/deb focal/main amd64 temurin-8-jdk amd64 8.0.382.0.0+5
2023/10/29 09:21:27 ui: 2023-10-29T09:21:27Z:     azure-arm.ubuntu20:   403  Forbidden [IP: 151.101.39.42 443]
2023/10/29 09:21:27 ui: 2023-10-29T09:21:27Z:     azure-arm.ubuntu20: Fetched 2290 kB in 2s (1344 kB/s)
2023/10/29 09:21:28 ui error: 2023-10-29T09:21:28Z: ==> azure-arm.ubuntu20: E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-8/temurin-8-jdk_8.0.382.0.0+5_amd64.deb  403  Forbidden [IP: 151.101.39.42 443]
2023/10/29 09:21:28 ui error: 2023-10-29T09:21:28Z: ==> azure-arm.ubuntu20: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

```

**Comment by lss4** [comment]
> It's NOT fixed! Using [these scripts](https://github.com/actions/runner-images/), I still get the error randomly.
> 
> ```
> 2023/10/29 09:21:25 ui: 2023-10-29T09:21:25Z:     azure-arm.ubuntu20: After this operation, 214 MB of additional disk space will be used.
> 2023/10/29 09:21:25 ui: 2023-10-29T09:21:25Z:     azure-arm.ubuntu20: Get:1 https://packages.adoptium.net/artifactory/deb focal/main amd64 adoptium-ca-certificates all 1.0.2-1 [2304 B]
> 2023/10/29 09:21:25 ui: 2023-10-29T09:21:25Z:     azure-arm.ubuntu20: Get:2 https://packages.adoptium.net/artifactory/deb focal/main amd64 temurin-8-jdk amd64 8.0.382.0.0+5 [84.8 MB]
> 2023/10/29 09:21:25 ui: 2023-10-29T09:21:25Z:     azure-arm.ubuntu20: Get:3 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 p11-kit-modules amd64 0.23.20-1ubuntu0.1 [231 kB]
> 2023/10/29 09:21:26 ui: 2023-10-29T09:21:26Z:     azure-arm.ubuntu20: Get:4 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 p11-kit amd64 0.23.20-1ubuntu0.1 [93.8 kB]
> 2023/10/29 09:21:26 ui: 2023-10-29T09:21:26Z:     azure-arm.ubuntu20: Get:5 http://azure.archive.ubuntu.com/ubuntu focal/main amd64 fonts-dejavu-extra all 2.37-1 [1953 kB]
> 2023/10/29 09:21:26 ui: 2023-10-29T09:21:26Z:     azure-arm.ubuntu20: Get:6 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 fonts-dejavu all 2.37-1 [3130 B]
> 2023/10/29 09:21:26 ui: 2023-10-29T09:21:26Z:     azure-arm.ubuntu20: Get:7 http://azure.archive.ubuntu.com/ubuntu focal/main amd64 java-common all 0.72 [6816 B]
> 2023/10/29 09:21:27 ui: 2023-10-29T09:21:27Z:     azure-arm.ubuntu20: Err:2 https://packages.adoptium.net/artifactory/deb focal/main amd64 temurin-8-jdk amd64 8.0.382.0.0+5
> 2023/10/29 09:21:27 ui: 2023-10-29T09:21:27Z:     azure-arm.ubuntu20:   403  Forbidden [IP: 151.101.39.42 443]
> 2023/10/29 09:21:27 ui: 2023-10-29T09:21:27Z:     azure-arm.ubuntu20: Fetched 2290 kB in 2s (1344 kB/s)
> 2023/10/29 09:21:28 ui error: 2023-10-29T09:21:28Z: ==> azure-arm.ubuntu20: E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-8/temurin-8-jdk_8.0.382.0.0+5_amd64.deb  403  Forbidden [IP: 151.101.39.42 443]
> 2023/10/29 09:21:28 ui error: 2023-10-29T09:21:28Z: ==> azure-arm.ubuntu20: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> ```

I just tried a wget for the deb and the link is working at the moment. The 403 error is a different thing from the `${VERSION}` issue.

The server is behaving a bit odd. Whenever I try to look at the info of a package version on the repo website (packages.adoptium.net), as soon as the "Builds" tab starts to load, I would receive several 403 errors ("You're not authorized to view this page.") which kicked me back to the package list with a 500 page followed shortly after. The "Location" tab itself (which contains the package links) appears fine but as I'm being kicked out I could only take a brief glance of it if I switch to that tab quick enough.

**Comment by karianna** [comment]
@gdams This is the other use case I think we need to resolve

**Comment by gdams** [comment]
> packages.adoptium.net

@lss4 just to confirm are you referring to this page: https://packages.adoptium.net/ui/builds/

it seems to load okay for me (without me being logged in)

**Comment by lss4** [comment]
> > packages.adoptium.net
> 
> @lss4 just to confirm are you referring to this page: https://packages.adoptium.net/ui/builds/
> 
> it seems to load okay for me (without me being logged in)

Not that... I was referring to the information page of a package. For example,

https://packages.adoptium.net/ui/packages/deb:%2F%2Ftemurin-17-jdk/17.0.9.0.0+9

The "Builds" tab does not have anything useful as I was mainly looking at the "Location" tab when the `${VERSION}` issue first surfaced. After staying at that page for a while I get kicked out by a series of 403 errors. Although at first I could stay a bit longer, after being kicked out for the first time, if I try to look at another package's information I get kicked out almost immediately.

So perhaps this part requires some kind of login and not really a bug?

**Comment by gdams** [comment]
> > > packages.adoptium.net
> > 
> > 
> > @lss4 just to confirm are you referring to this page: https://packages.adoptium.net/ui/builds/
> > it seems to load okay for me (without me being logged in)
> 
> Not that... I was referring to the information page of a package. For example,
> 
> https://packages.adoptium.net/ui/packages/deb:%2F%2Ftemurin-17-jdk/17.0.9.0.0+9
> 
> The "Builds" tab does not have anything useful as I was mainly looking at the "Location" tab when the `${VERSION}` issue first surfaced. After staying at that page for a while I get kicked out by a series of 403 errors. Although at first I could stay a bit longer, after being kicked out for the first time, if I try to look at another package's information I get kicked out almost immediately.
> 
> So perhaps this part requires some kind of login and not really a bug?

I see the same bug when going directly to artifactory (and excluding the CDN) - https://adoptium.jfrog.io/ui/packages/deb:%2F%2Ftemurin-17-jdk/17.0.9.0.0+9

I'll raise a JFrog bug but I don't think this will be causing 401 errors for people downloading the latest debian installers

**Comment by lhotari** [comment]
I'm hitting a "Error reading from server. Remote end closed connection" issue, commented about that on https://github.com/adoptium/installer/issues/754#issuecomment-1785810245

**Comment by jarppe** [comment]
I have been successfully installing temurin-21-jdk on amd64 machines for some time now, but now I get:
```
E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-21/temurin-21-jdk_21.0.1.0.0%2b12_amd64.deb  403  Forbidden [IP: 151.101.3.42 443]
```

**Comment by gdams** [comment]
@swi-jared looking at your log it suggests that Fastly has cached a partial request rather than a full one, I'm still working with Fastly to get this fixed as it's a known bug.

**Comment by PhilipGarnero** [comment]
Same issue with temurin 17 on my side. It used to arise from time to time but it's been completely out for the last hour.

**Comment by lhotari** [comment]
I'm hitting problems in apache/pulsar's CI builds.

```
[INFO] DOCKER> Err:30 https://packages.adoptium.net/artifactory/deb jammy/main amd64 temurin-17-jdk amd64 17.0.9.0.0+9
  403  Forbidden [IP: 146.75.31.42 443]
[INFO] DOCKER> Fetched 6128 kB in 0s (15.7 MB/s)
[INFO] DOCKER> [91mE: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-17/temurin-17-jdk_17.0.9.0.0%2b9_amd64.deb  403  Forbidden [IP: 146.75.31.42 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

```
  Error reading from server. Remote end closed connection [IP: 146.75.39.42 443]
[INFO] DOCKER> Fetched 6128 kB in 2s (2886 kB/s)
[INFO] DOCKER> [91mE: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-17/temurin-17-jdk_17.0.9.0.0%2b9_amd64.deb  Error reading from server. Remote end closed connection [IP: 146.75.39.42 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

I noticed a very short initial timeout of 250 milliseconds in the Debian apt code:
https://salsa.debian.org/apt-team/apt/-/blob/c555d8f1ae31d1f511bf811640423231b75a8e13/methods/connect.cc#L457-464
It seems to iterate through all DNS resolved IPs and have the 250 ms timeout. After this, the timeout is set to 30 seconds.
I wonder if this 250 milliseconds timeout could be causing extra load on servers?

I'm trying with 2000 milliseconds here: https://github.com/apache/pulsar/pull/21727 (I haven't checked results yet).

**Comment by karianna** [comment]
> I'm hitting problems in apache/pulsar's CI builds.
> 
> ```
> [INFO] DOCKER> Err:30 https://packages.adoptium.net/artifactory/deb jammy/main amd64 temurin-17-jdk amd64 17.0.9.0.0+9
>   403  Forbidden [IP: 146.75.31.42 443]
> [INFO] DOCKER> Fetched 6128 kB in 0s (15.7 MB/s)
> [INFO] DOCKER> [91mE: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-17/temurin-17-jdk_17.0.9.0.0%2b9_amd64.deb  403  Forbidden [IP: 146.75.31.42 443]
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> ```
> 
> ```
>   Error reading from server. Remote end closed connection [IP: 146.75.39.42 443]
> [INFO] DOCKER> Fetched 6128 kB in 2s (2886 kB/s)
> [INFO] DOCKER> [91mE: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-17/temurin-17-jdk_17.0.9.0.0%2b9_amd64.deb  Error reading from server. Remote end closed connection [IP: 146.75.39.42 443]
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> ```
> 
> I noticed a very short initial timeout of 250 milliseconds in the Debian apt code: https://salsa.debian.org/apt-team/apt/-/blob/c555d8f1ae31d1f511bf811640423231b75a8e13/methods/connect.cc#L457-464 It seems to iterate through all DNS resolved IPs and have the 250 ms timeout. After this, the timeout is set to 30 seconds. I wonder if this 250 milliseconds timeout could be causing extra load on servers?
> 
> I'm trying with 2000 milliseconds here: [apache/pulsar#21727](https://github.com/apache/pulsar/pull/21727) (I haven't checked results yet).
> 
> Trying with a apt config file /etc/apt/apt.conf.d/99timeout_and_retries with
> 
> ```
> Acquire::http::Timeout 30;
> Acquire::http::ConnectionAttemptDelayMsec 2000;
> Acquire::https::Timeout 30;
> Acquire::https::ConnectionAttemptDelayMsec 2000;
> Acquire::ftp::Timeout 30;
> Acquire::ftp::ConnectionAttemptDelayMsec 2000;
> Acquire::Retries 15;
> ```

@gdams maybe some clues here as to what is going on

**Comment by mezpahlan** [comment]
Hi there I think I'm having the same issues and have no idea how to get past this. Is there an easy workaround or timeline you can share for when this is supposed to work. I just want to be able to update my system without these error messages. Cheers :+1: .

![image](https://github.com/adoptium/installer/assets/4974178/139a2b0f-5f43-4094-a1fe-36a61dd06f5a)

**Comment by mrairzuk** [comment]
Can approve, issue is happening again with the new temurin-17-jdk version:
```
Err:1 https://packages.adoptium.net/artifactory/deb jammy/main amd64 temurin-17-jdk amd64 17.0.10.0.0+7
  400  Bad Request [IP: 151.101.247.42 443]
E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-${VERSION}/temurin-17-jdk_17.0.10.0.0%2b7_amd64.deb  400  Bad Request [IP: 151.101.247.42 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by iAweX** [comment]
Same problem. And there are no package in repo.

![image](https://github.com/adoptium/installer/assets/50710418/960ac877-74db-45f1-9cd3-05356f894a58)

![image](https://github.com/adoptium/installer/assets/50710418/1a65c94a-e62d-4b39-a74a-4b68649b4b70)

**Comment by ByCzech** [comment]
> We've manually replaced some of the missing packages (root cause analysis is still ongoing) so please do try again and let us know!

Still persist at least on JRE 17 package:

Err:1 https://packages.adoptium.net/artifactory/deb bookworm/main amd64 temurin-17-jre amd64 17.0.10.0.0+7
  400  Bad Request [IP: 151.101.195.42 443]
E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-${VERSION}/temurin-17-jre_17.0.10.0.0%2b7_amd64.deb  400  Bad Request [IP: 151.101.195.42 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by mrairzuk** [comment]
> We've manually replaced some of the missing packages (root cause analysis is still ongoing) so please do try again and let us know!

Just successfully updated JDK 17
```
Get:1 https://packages.adoptium.net/artifactory/deb jammy/main amd64 temurin-17-jdk amd64 17.0.10.0.0+7 [166 MB]
Fetched 166 MB in 1min 40s (1659 kB/s)
```

**Comment by ByCzech** [comment]
Right now new problem with JDK 21 + JRE 17 remain (see above):

Err:1 https://packages.adoptium.net/artifactory/deb bookworm/main amd64 temurin-17-jre amd64 17.0.10.0.0+7
  400  Bad Request [IP: 151.101.3.42 443]
Err:2 https://packages.adoptium.net/artifactory/deb bookworm/main amd64 temurin-21-jdk amd64 21.0.2.0.0+13
  400  Bad Request [IP: 151.101.3.42 443]
E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-${VERSION}/temurin-17-jre_17.0.10.0.0%2b7_amd64.deb  400  Bad Request [IP: 151.101.3.42 443]
E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-${VERSION}/temurin-21-jdk_21.0.2.0.0%2b13_amd64.deb  400  Bad Request [IP: 151.101.3.42 443]

**Comment by gdams** [comment]
> E: Failed to fetch [https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-${VERSION}/temurin-17-jre_17.0.10.0.0%2b7_amd64.deb](https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-$%7BVERSION%7D/temurin-17-jre_17.0.10.0.0%2b7_amd64.deb) 400 Bad Request [IP: 151.101.3.42 443]
E: Failed to fetch [https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-${VERSION}/temurin-21-jdk_21.0.2.0.0%2b13_amd64.deb](https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-$%7BVERSION%7D/temurin-21-jdk_21.0.2.0.0%2b13_amd64.deb) 400 Bad Request [IP: 151.101.3.42 443]

@ByCzech those URL's look broken (see the `$%7BVERSION%7D`) I'll check this out

**Comment by ByCzech** [comment]
> > E: Failed to fetch [https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-${VERSION}/temurin-17-jre_17.0.10.0.0%2b7_amd64.deb](https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-$%7BVERSION%7D/temurin-17-jre_17.0.10.0.0%2b7_amd64.deb) 400 Bad Request [IP: 151.101.3.42 443]
> > E: Failed to fetch [https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-${VERSION}/temurin-21-jdk_21.0.2.0.0%2b13_amd64.deb](https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-$%7BVERSION%7D/temurin-21-jdk_21.0.2.0.0%2b13_amd64.deb) 400 Bad Request [IP: 151.101.3.42 443]
> 
> @ByCzech those URL's look broken (see the `$%7BVERSION%7D`) I'll check this out

I know, this happened in past too. See above https://github.com/adoptium/installer/issues/766#issue-1965166105

**Comment by ByCzech** [comment]
Problem seems solved for me. This try i successfully upgraded temurin-17-jre temurin-21-jdk temurin-21-jre temurin-8-jdk packages.

**Comment by mezpahlan** [comment]
Hi thanks all for the help trying to get this working. I've tried again from my home connection and it still didn't work (updating JDK 17). This is on my work laptop which got me thinking maybe it is my companies VPN messing things up. 

I turned off my VPN and tried the update again and this time it has worked :balloon: .

![image](https://github.com/adoptium/installer/assets/4974178/974d6eea-b6d5-42c6-b0cd-aad159aa6ab1)

So for everyone else with the same problem maybe try turning off your VPN? I still think it should work when the VPN is connected but this might be an easy workaround?

**Comment by emileekane** [comment]
Hello, Just tried installing `temurin-21-jdk` and got this error.
System : Ubuntu 22.04.3 LTS
```
user@pcdata08:~$ sudo apt-get install temurin-21-jdk
[sudo] password for ekane:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package temurin-21-jdk
```

Is there a workaround solution ?

**Comment by dmayo3** [comment]
Just had this issue with debian bookworm while trying to install temurin 21.

Weirdly none of the packages would be available to install unless I ran the following command twice 🤔 

```
add-apt-repository https://packages.adoptium.net/artifactory/deb/
```

After that it worked.

**Comment by dmayo3** [comment]
For those seeing `403  Forbidden [IP: x.x.x.x]` type errors, there seems to be some sort of rate limiting in place.

I was seeing this a lot when rebuilding docker images a lot that included the temurin package.

I would have to wait a while before retrying again.

Now I avoid reinstalling it as often and it hasn't been an issue for me lately.

**Comment by Codes301** [comment]
Step 2 does not work for me on Linux Mint Debian, LMDE 6 "Faye"

"Download the Eclipse Adoptium GPG key:"

`
echo "deb https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | tee /etc/apt/sources.list.d/adoptium.list
`

It results in this:
tee: /etc/apt/sources.list.d/adoptium.list: Permission denied
deb https://packages.adoptium.net/artifactory/deb faye main

**Comment by karianna** [comment]
> Step 2 does not work for me on Linux Mint Debian, LMDE 6 "Faye"
> 
> "Download the Eclipse Adoptium GPG key:"
> 
> `echo "deb https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | tee /etc/apt/sources.list.d/adoptium.list`
> 
> It results in this: tee: /etc/apt/sources.list.d/adoptium.list: Permission denied deb 

You need to add sudo to the tee command

`echo "deb https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | sudo tee /etc/apt/sources.list.d/adoptium.list`

**Comment by IAISI** [comment]
This is still an issue, on Debian 12. Forcing apt to use ipv4 fixed the issue for some reason...

apt-get -o Acquire::ForceIPv4=true install temurin-21-jdk

**Comment by mixman68** [comment]
`8.782 Get:2 https://packages.adoptium.net/artifactory/deb focal/main amd64 adoptium-ca-certificates all 1.0.4-1 [2,368 B]
9.484 Err:3 https://packages.adoptium.net/artifactory/deb focal/main amd64 temurin-11-jdk amd64 11.0.25.0.0+9
9.484   503  Service Unavailable [IP: 104.18.21.66 443]
9.488 Fetched 9,184 B in 1s (9,177 B/s)
9.489 E: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-11/temurin-11-jdk_11.0.25.0.0+9_amd64.deb  503  Service Unavailable [IP: 104.18.21.66 443]
9.489 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing`

seems to be back
